env:
  browser: true
  commonjs: true
  es2021: true
  jest: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
rules: {
  "no-console": "off",
  "no-underscore-dangle": "off",
  'linebreak-style': "off",
  'no-await-in-loop': "off",
  'max-len': "off",
  'camelcase': "off",
  'no-shadow': "off",
  'object-shorthand': "off",
}
